# Generated by Django 4.2.30 on 2026-05-13 13:39

from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_alter_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(storage=study.models.SmartCloudinaryStorage(), upload_to=study.models.get_resource_filename),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('image', 'Image'), ('video', 'Video'), ('link', 'External Link'), ('notes', 'Study Notes')], max_length=20),
        ),
    ]
