# Generated by Django 4.2.30 on 2026-04-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_schedulingpreference_busyslot'),
        ('users', '0004_studyrequest'),
    ]

    operations = [
    ]
