# Generated by Django 4.2.30 on 2026-05-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20260421_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulingpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='BusySlot',
        ),
        migrations.DeleteModel(
            name='SchedulingPreference',
        ),
    ]
